#!/bin/bash --login

# If the TDSQL_PATH environment variable is not defined follow the symlinks to find it.
if ([ -z "${TDSQL_PATH}" ]) then
  # Trick for getting the script dir when being executed by a symlink
  # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
  pushd . > /dev/null
  TDSQL_PATH="${BASH_SOURCE[0]}";
  if ([ -h "${TDSQL_PATH}" ]) then
    while([ -h "${TDSQL_PATH}" ]) do cd `dirname "$TDSQL_PATH"`; TDSQL_PATH=`readlink "${TDSQL_PATH}"`; done
  fi
  cd `dirname ${TDSQL_PATH}` > /dev/null
  TDSQL_PATH=`pwd`;
  popd  > /dev/null
fi

JRUBY_PATH=`which jruby`;

# which jruby
# echo "JRUBY=$JRUBY_PATH"
# rvm use jruby > /dev/null
$JRUBY_PATH $TDSQL_PATH/main.rb "$@"
